//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace SelectivasEnSucursales.Entity
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class TrazabilidadEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto TrazabilidadEntities usando la cadena de conexión encontrada en la sección 'TrazabilidadEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public TrazabilidadEntities() : base("name=TrazabilidadEntities", "TrazabilidadEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto TrazabilidadEntities.
        /// </summary>
        public TrazabilidadEntities(string connectionString) : base(connectionString, "TrazabilidadEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto TrazabilidadEntities.
        /// </summary>
        public TrazabilidadEntities(EntityConnection connection) : base(connection, "TrazabilidadEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<trazabilidad> trazabilidad
        {
            get
            {
                if ((_trazabilidad == null))
                {
                    _trazabilidad = base.CreateObjectSet<trazabilidad>("trazabilidad");
                }
                return _trazabilidad;
            }
        }
        private ObjectSet<trazabilidad> _trazabilidad;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet trazabilidad. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTotrazabilidad(trazabilidad trazabilidad)
        {
            base.AddObject("trazabilidad", trazabilidad);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TrazabilidadModel", Name="trazabilidad")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class trazabilidad : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto trazabilidad.
        /// </summary>
        /// <param name="numero_etiqueta">Valor inicial de la propiedad numero_etiqueta.</param>
        /// <param name="folio_salida">Valor inicial de la propiedad folio_salida.</param>
        /// <param name="tipo_salida">Valor inicial de la propiedad tipo_salida.</param>
        /// <param name="fecha_embarque">Valor inicial de la propiedad fecha_embarque.</param>
        /// <param name="propietario">Valor inicial de la propiedad propietario.</param>
        /// <param name="cliente">Valor inicial de la propiedad cliente.</param>
        public static trazabilidad Createtrazabilidad(global::System.String numero_etiqueta, global::System.String folio_salida, global::System.String tipo_salida, global::System.DateTime fecha_embarque, global::System.String propietario, global::System.String cliente)
        {
            trazabilidad trazabilidad = new trazabilidad();
            trazabilidad.numero_etiqueta = numero_etiqueta;
            trazabilidad.folio_salida = folio_salida;
            trazabilidad.tipo_salida = tipo_salida;
            trazabilidad.fecha_embarque = fecha_embarque;
            trazabilidad.propietario = propietario;
            trazabilidad.cliente = cliente;
            return trazabilidad;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String numero_etiqueta
        {
            get
            {
                return _numero_etiqueta;
            }
            set
            {
                if (_numero_etiqueta != value)
                {
                    Onnumero_etiquetaChanging(value);
                    ReportPropertyChanging("numero_etiqueta");
                    _numero_etiqueta = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("numero_etiqueta");
                    Onnumero_etiquetaChanged();
                }
            }
        }
        private global::System.String _numero_etiqueta;
        partial void Onnumero_etiquetaChanging(global::System.String value);
        partial void Onnumero_etiquetaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String folio_salida
        {
            get
            {
                return _folio_salida;
            }
            set
            {
                Onfolio_salidaChanging(value);
                ReportPropertyChanging("folio_salida");
                _folio_salida = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("folio_salida");
                Onfolio_salidaChanged();
            }
        }
        private global::System.String _folio_salida;
        partial void Onfolio_salidaChanging(global::System.String value);
        partial void Onfolio_salidaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String folio_compra
        {
            get
            {
                return _folio_compra;
            }
            set
            {
                Onfolio_compraChanging(value);
                ReportPropertyChanging("folio_compra");
                _folio_compra = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("folio_compra");
                Onfolio_compraChanged();
            }
        }
        private global::System.String _folio_compra;
        partial void Onfolio_compraChanging(global::System.String value);
        partial void Onfolio_compraChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tipo_salida
        {
            get
            {
                return _tipo_salida;
            }
            set
            {
                Ontipo_salidaChanging(value);
                ReportPropertyChanging("tipo_salida");
                _tipo_salida = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tipo_salida");
                Ontipo_salidaChanged();
            }
        }
        private global::System.String _tipo_salida;
        partial void Ontipo_salidaChanging(global::System.String value);
        partial void Ontipo_salidaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_embarque
        {
            get
            {
                return _fecha_embarque;
            }
            set
            {
                Onfecha_embarqueChanging(value);
                ReportPropertyChanging("fecha_embarque");
                _fecha_embarque = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_embarque");
                Onfecha_embarqueChanged();
            }
        }
        private global::System.DateTime _fecha_embarque;
        partial void Onfecha_embarqueChanging(global::System.DateTime value);
        partial void Onfecha_embarqueChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String propietario
        {
            get
            {
                return _propietario;
            }
            set
            {
                OnpropietarioChanging(value);
                ReportPropertyChanging("propietario");
                _propietario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("propietario");
                OnpropietarioChanged();
            }
        }
        private global::System.String _propietario;
        partial void OnpropietarioChanging(global::System.String value);
        partial void OnpropietarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cliente
        {
            get
            {
                return _cliente;
            }
            set
            {
                OnclienteChanging(value);
                ReportPropertyChanging("cliente");
                _cliente = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cliente");
                OnclienteChanged();
            }
        }
        private global::System.String _cliente;
        partial void OnclienteChanging(global::System.String value);
        partial void OnclienteChanged();

        #endregion

    
    }

    #endregion

    
}
